title: ahngbeom
description: "My Journey as a Developer"
logo_img: "https://avatars.githubusercontent.com/u/57256332?v=4"
profile_img: "https://avatars.githubusercontent.com/u/57256332?v=4"

# Social Links
email: bbu0704@gmail.com
github_username: ahngbeom
# twitter_username: twitter
# instagram_username: instagram
# linkedin_username: linkedin
# facebook_username: facebook

# External API
giscus_repo: "Ahngbeom/ahngbeom.github.io"
giscus_repoId: "R_kgDOPejN_A"
giscus_category: "Announcements"
giscus_categoryId: "DIC_kwDOPejN_M4Cukk3"
goatcounter_code: ahngbeom-github-io
google_analytics: G-5TF76QSFJ3

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  introduction:
    output: true
    permalink: /:collection/:introduction
    order: 1
  pages:
    output: true
    permalink: /:path.html
    sort_by: title
    # 수동 정렬을 위한 기본값 설정
    defaults:
      values:
        order: 999

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
